/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native_WindowInformation */

#ifndef _Included_Native_WindowInformation
#define _Included_Native_WindowInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native_WindowInformation
 * Method:    GetNativeWindowBounds
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Native_WindowInformation_GetNativeWindowBounds
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
